### ISSUE TITLE
Customize the Jbrowse menu

### ISSUE THREAD

**Issue by samrichca** [overture-stack/dms-jbrowse-components#14]
Add a plugin for customizing the Jbrowse main menu in the top left of the visualization.

This was added in [this commit](https://github.com/overture-stack/dms-jbrowse-components/commit/161e0ce17d9bd454280152831f70220efbde8bba) but removed because we can't transpile an ES6 class down to ES5 in order to build our Jbrowse wrapper for NPM. Need to investigate alternatives to this syntax with the Jbrowse team.

**Comment by b-f-chan** [comment]
Closing as not required for now.  We have decided to go with the default J-Browse main menu.  If requirements for customization come in future, we will treat these as post MVP enhancements.
