### ISSUE TITLE
Jbrowse: Move config to DMS-UI, prep for NPM

### ISSUE THREAD

**Issue by samrichca** [overture-stack/dms-jbrowse-components#19]
Take any config in DMS-Jbrowse components that is related to which files are loaded, and move it to DMS-UI, before publishing DMS-jbrowse to NPM.

Examples
- URLs for human genome
- Default Jbrowse session
- Assembly (i.e. which version of human genome)

Make any other changes needed for NPM.

**Comment by b-f-chan** [comment]
This will be a post-MVP enhancement

**Comment by b-f-chan** [comment]
Reviewed, merged, closing
