### ISSUE TITLE
Add Warning Message that Site Not Optimized for Mobile

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/dms-jbrowse-components#26]
Add warning message to indicate the site is not optimized for mobile

Idea --> Use a media query to determine form factor/dimensions and when to display message

Long-term --> Design mobile version of site, but this may be low priority

**Comment by b-f-chan** [comment]
@patrickdsantos to do design first on the message, assigning to @patrickdsantos

**Comment by b-f-chan** [comment]
The error message is unable to span the entire length (particularly the filter panel) without Arranger changes.  This is not worth a change in Arranger for now.  We'll have the message be an overlay, just span the portion of the query bar, overlap the content, and have a close/dismiss button.  This was agreed with @samrichca @patrickdsantos

**Comment by samrichca** [comment]
https://github.com/overture-stack/dms-ui/pull/178

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazl6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9dae417f3359211bfe34ae611230c7cb3a11a68a/image.png)

**Comment by b-f-chan** [comment]
Unable to get this error message to show up on QA, whether by shrinking my browser below 1024px, or using a mobile browser simulator extension in Chrome

**Comment by b-f-chan** [comment]
Pending infra config change on QA so this can be tested, since this is enabled by a feature flag which is currently disabled on QA

**Comment by b-f-chan** [comment]
Config changed deployed, tested successfullly on QA, mobile warning message displays when < 1024 px, closing
