### ISSUE TITLE
Quick Test Circular View with Existing VCFs (with Translocations)

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/dms-jbrowse-components#39]
Quickly test that circular view can be loaded in DMS with some existing VCFs with translocations

Resources provided by J-Browse and Bioinfo teams:

- http://schatz-lab.org/publications/SKBR3/ (see Variants discovered with Sniffles:
reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.bam.sniffles1kb_auto_l8_s5_noalt.vcf.gz)

- https://dcc.icgc.org/releases/PCAWG/consensus_sv (PCAWG public data)

Bioinfo to assist with loading files into Overture QA

**Comment by samrichca** [comment]
file uuid on qa is e6816386-efbc-5269-a845-9978fdd73ac5

**Comment by samrichca** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamVoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6595cdce2d1f29f0276a747cba81159c5cb2fdb4/image.png)

**Comment by samrichca** [comment]
- renamed jbrowse to genome viewer, removed logo
- fixed mobile warning message

**Comment by b-f-chan** [comment]
Test worked, closing
