### ISSUE TITLE
Implement File Selection Logic

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/dms-jbrowse-components#7]
Implement logic for how to select applicable files for the J-Browse component.

**This entails:**

- [x] Add logic to enable J-Browse button ONLY when:
    - [x] Minimum of ONE applicable file types are selected (BAM, VCF)
    - [x] Selected files does not exceed maximum # of files allowed (for now set a configurable but arbitrary number; not a performance issue but more a UX issue)
- [x] Add tooltip for J-Browse button disabled state, explaining how to make use of the button - See mockup for suggested text
- [x] Add logic to pass selected files into J-Browse component (TBD whether this is file ID, file name, or something else)
- [x] Ensure the correct data is being returned for both J-Browse and the "Selected Files" table

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/0614fa7f-9acf-465e-81ca-fde9bf4e7b4c)

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/0fd818c0-82f8-414d-9417-996b8a4cb3dd)

**Comment by samrichca** [comment]
for the last two points:
- Add logic to pass selected files into J-Browse component
- Ensure the correct data is being returned for both J-Browse and the "Selected Files" table

to get data for jbrowse, in the jbrowse tab, we'll look at the selected rows array in the table context, and make a request to arranger/song to get metadata for the selected files. then we'll filter down to the files that work for jbrowse, and make a request to score to get the file URLs.

**Comment by b-f-chan** [comment]
Tested successfully in QA, closing
