### ISSUE TITLE
Add "Selected Files" Table Below J-Browse Component

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/dms-jbrowse-components#8]
Add the "Selected Files" table below the J-Browse component

**This entails:**

- [x] Add the table itself
- [ ] Enable sorting on the table (no pagination required)
- [x] Add Hide/Show button
- [x] Display # of files selected
- [x] Ensure no hyperlinks are provided (this is just a static table)

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/c1a0edc2-ac48-4f43-a38a-3cc49e98b5d9)

**Comment by samrichca** [comment]
I didn't add sorting because this isn't using our react table API.

**Comment by b-f-chan** [comment]
Sorting will be post MVP enhancement.  All other items tested successfully in QA, closing
